# Uncomment the next line to define a global platform for your project
platform :ios, 8.0

target 'IfSampler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IfSampler
  #pod 'lf'
  pod 'lf', :git => 'git@github.com:shogo4405/lf.swift.git', :branch => 'master'


  target 'IfSamplerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IfSamplerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
