# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTaskSampler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTaskSampler

  pod 'SwiftTask', :git => 'https://github.com/ReactKit/SwiftTask', :branch => 'swift/3.0'
end
