# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JTSImageViewControllerSampler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JTSImageViewControllerSampler
  pod 'JTSImageViewController'

  target 'JTSImageViewControllerSamplerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JTSImageViewControllerSamplerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
