# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActionSampler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActionSampler
  pod 'Action'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'ActionSamplerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ActionSamplerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
